service: serverless-example

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  profile: maureyes.dev
  region: us-east-1

functions:
  main:
    handler: src/aws/utils/lambda-handlers.moviesService
    events:
      - http:
          method: any
          path: /movies/gql
          cors: true