service: mau-micro-services

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-localstack
  - serverless-lift

custom:
  localstack:
    debug: true
    stages:
      - local
  envs:
    handlersPath: src/aws/utils/lambda-handlers

provider:
  name: aws
  runtime: nodejs16.x
  profile: maureyes.dev
  region: us-east-1

functions:
  movies-service:
    handler: ${self:custom.envs.handlersPath}.moviesService
    events:
      - http:
          method: any
          path: /movies/gql
          cors: true

constructs:
  movies-queue:
    type: queue
    worker:
      handler: ${self:custom.envs.handlersPath}.moviesJobs